[theme]

primaryColor="#9b59b6"
backgroundColor="#ced6e0"
secondaryBackgroundColor="#e0e0ef"
textColor="#262730"
font="sans serif"

# primaryColor="#A9584C"
# backgroundColor="#F7E8A1"
# secondaryBackgroundColor="#EB804C"
# textColor="#042C3B"
# font="sans serif"

